trigger:
  branches:
    include: [ main, develop ]
  paths:
    include:
      - src/**
      - tests/**
      - Makefile
      - .clang-format
      - .clang-tidy

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndTest
  displayName: Build & Test
  jobs:
  - job: build_test
    steps:
    - task: Bash@3
      displayName: Install toolchain
      inputs:
        targetType: inline
        script: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang-format clang-tidy
    - task: Bash@3
      displayName: Build
      inputs:
        targetType: inline
        script: |
          make clean
          make -j
    - task: Bash@3
      displayName: Run unit tests
      inputs:
        targetType: inline
        script: make test
    - task: Bash@3
      displayName: Format check
      inputs:
        targetType: inline
        script: make format-check
    - task: Bash@3
      displayName: Static analysis
      inputs:
        targetType: inline
        script: make tidy
    - task: PublishBuildArtifacts@1
      displayName: Publish lib
      inputs:
        PathtoPublish: 'libutil.a'
        ArtifactName: 'libutil'
        publishLocation: 'Container'
